name: Deploy Portal Electoral to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Static Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::279566174232:role/github-actions-portal-electoral-deploy-role
          aws-region: us-east-1

      - name: Upload static website files to S3
        run: |
          aws s3 sync css s3://portal-electoral-tse-prod/css --delete
          aws s3 sync js s3://portal-electoral-tse-prod/js --delete
          aws s3 sync data s3://portal-electoral-tse-prod/data --delete
          aws s3 sync assets s3://portal-electoral-tse-prod/assets --delete

          aws s3 cp index.html s3://portal-electoral-tse-prod/index.html
          aws s3 cp resultados.html s3://portal-electoral-tse-prod/resultados.html
          aws s3 cp departamentos.html s3://portal-electoral-tse-prod/departamentos.html
          aws s3 cp reportes.html s3://portal-electoral-tse-prod/reportes.html

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EA0BUF10ANEZL \
            --paths "/*"